import "./smooth-scroll/smooth-scroll";
import "./dropdown-nav/dropdown-nav";
import "./fly-tags/fly-tags";
import "./slick-slider/slick-slider";
import "./popup/popup";
import "./popup/popup-call";
import "./popup/popup-thanks";
import "./input-mask/input-mask";
import "./send/send";
